'use strict';
const $ = (s, root = document) => root.querySelector(s);
const icons = {
  scan:'M4 9V4h5M15 4h5v5M20 15v5h-5M9 20H4v-5M7 12h10',
  file:'M7 3h7l4 4v14H7zM14 3v5h4M10 12h5M10 16h5',
  search:'M20 20l-5-5M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0',
  plus:'M12 5v14M5 12h14', close:'M6 6l12 12M6 18L18 6',
  back:'M15 5l-7 7 7 7', next:'M9 5l7 7-7 7',
  folder:'M3 6h7l2 3h9v11H3z', tools:'M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z',
  settings:'M12 8a4 4 0 1 1 0 8 4 4 0 0 1 0-8M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M5 19l2-2M17 7l2-2',
  camera:'M3 7h5l2-3h4l2 3h5v13H3zM16 13a4 4 0 1 1-8 0 4 4 0 0 1 8 0',
  import:'M12 3v12M7 10l5 5 5-5M4 15v6h16v-6',
  id:'M3 5h18v14H3zM7 9h3v4H7zM6 16h5M14 9h4M14 13h4',
  video:'M3 5h12v14H3zM15 10l6-4v12l-6-4',
  photo:'M3 3h18v18H3zM3 17l6-6 4 4 3-3 5 5M16 7h.01',
  check:'M5 12l4 4L19 6', more:'M5 12h.01M12 12h.01M19 12h.01',
  rotate:'M4 9a8 8 0 1 1 1 9M4 3v6h6', up:'M6 14l6-6 6 6', down:'M6 10l6 6 6-6',
  trash:'M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7',
  text:'M4 4h16M12 4v16M8 20h8', flash:'M13 2L5 14h6l-1 8 9-13h-7z',
  copy:'M8 8h12v13H8zM4 16V3h12', lock:'M7 10V7a5 5 0 0 1 10 0v3M5 10h14v11H5z',
  edit:'M4 16L16 4l4 4L8 20H4zM13 7l4 4', share:'M12 15V3M7 8l5-5 5 5M5 13v8h14v-8',
  play:'M8 5l11 7-11 7z'
};
function icon(name){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[name] || icons.file}"/></svg>`;}
function esc(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
const screens = [
  ['library','Library','YOUR EVERYDAY WORKSPACE','Capture, find and organize.','A calm home for the documents that matter. Local files come first, with no account standing between you and your next scan.',['Start a new document scan.','Search the sample library.','Import a fictional sample.']],
  ['capture','Capture','A BETTER FIRST SHOT','Point. Hold. Keep.','Capture stays focused: one shutter, clear guidance and a growing page count. Document, ID, photo and video modes share one entry point.',['Tap the shutter to add a page.','Toggle auto capture or flash.','Tap Done to adjust the crop.']],
  ['crop','Crop & straighten','GET THE EDGES RIGHT','Every corner counts.','Perspective correction has a manual fallback. Large corner targets, reset and nudge controls make precise crops accessible.',['Drag a corner or select it.','Use arrows for fine adjustment.','Rotate, then apply the crop.']],
  ['filters','Document filters','READABILITY, YOUR WAY','Make the page clearer.','A restrained default with room to adjust. Preview filters without losing the original, then apply the same enhancement to a whole batch.',['Compare Original and Clean Color.','Adjust filter strength.','Apply to all pages and save.']],
  ['id','ID copy','BOTH SIDES, ONE PLACE','A copy made simple.','A guided front-and-back flow keeps sides organized. Review the layout and optionally add a purpose watermark before export.',['Capture each sample side.','Switch to a passport template.','Add a copy-purpose watermark.']],
  ['video','Video scan','LESS STOPPING, MORE SCANNING','Find the best frames.','A video becomes a set of candidate pages. Keep the clear frames, review similar pages and decide what belongs in your document.',['Run the sample analysis.','Toggle selected page candidates.','Replace a frame and create pages.']],
  ['ocr','Extract text','FROM PIXELS TO WORDS','Text you can work with.','An editable transcript alongside its source. Recognition is a starting point; users can review and correct before reusing the text.',['Edit the sample transcript.','Save your corrections.','Copy text or return to pages.']],
  ['pages','Page organizer','THE DOCUMENT COMES TOGETHER','In the right order.','Reorder, rotate, annotate and add pages before export. The page collection remains editable with every original preserved.',['Move or duplicate a page.','Add a sample text note.','Extract text or export the PDF.']],
  ['export','Export & share','READY TO LEAVE THE APP','A file that fits.','Choose the right format and quality for the destination. See progress, cancel safely and share only after a complete file exists.',['Switch PDF, images and text.','Change paper size and quality.','Try a simulated export or cancel.']],
  ['photo','Photo studio','A LITTLE MORE LIGHT','Keep the feeling.','Photo styles are separate from document cleanup. Tweak color and exposure, compare with the original and save a new copy.',['Choose Warm or Mono.','Adjust exposure and saturation.','Compare the original and save.']],
  ['tools','Tools','A USEFUL LITTLE TOOLBOX','Room to grow.','Everyday document actions are close at hand. More specialized PDF, video and 3D features have an explicit place in the roadmap.',['Open a document or ID flow.','Explore planned tool descriptions.','Return to your library.']],
  ['settings','Settings','YOUR APP, YOUR DEFAULTS','Private by default.','Manage quality, language and local storage. Permissions and interrupted work have useful recovery paths instead of dead ends.',['Change the default paper size.','Preview a denied-camera state.','Inspect storage and model errors.']]
];
const state = {
  screen:'library', folder:'All', query:'', captured:0, auto:true, flash:false,
  filter:'Clean Color', strength:70, before:false, applyAll:false,
  crop:[[.17,.08],[.83,.08],[.83,.92],[.17,.92]], corner:0, rotation:0,
  template:'Card front & back', front:false, back:false, idSwapped:false, watermark:'',
  selectedFrames:new Set([0,1,3,5]), videoAnalyzed:true, replaced:false,
  transcript:'FIELD NOTES\n\nA slower kind of weekend\n\nMake space for the things that matter. A walk through the neighborhood, a shared meal, a little time away from a screen.\n\nRemember to bring:\n• A notebook\n• Something to read\n• A curious mind',
  pages:[{id:1,name:'Field notes',rotation:0},{id:2,name:'Weekend checklist',rotation:0},{id:3,name:'Places to explore',rotation:0}], nextId:4,
  filterSaved:'Clean Color', format:'PDF', quality:'Balanced', paper:'A4', filename:'Weekend notes', searchable:true,
  photoStyle:'Natural', exposure:0, saturation:100, photoBefore:false,
  docs:[{title:'Weekend notes',pages:3,date:'Today, 9:32 AM',folder:'Personal'},{title:'Project outline',pages:5,date:'Yesterday',folder:'Work'},{title:'ID copy · sample',pages:1,date:'28 Sep 2026',folder:'IDs'}],
  undoPages:null, modelReady:true
};
let timer=null, toastTimer=null, lastFocus=null;
function paper(){return `<article class="paper"><div class="paper-brand">FIELD / NOTES</div><h3>A slower kind<br>of weekend.</h3><p>Make space for the things that matter.<br>A walk, a shared meal, a little time away.</p><hr><div class="paper-line"></div><div class="paper-line"></div><div class="paper-line short"></div><br><div class="paper-line"></div><div class="paper-line short"></div><div class="paper-foot">THOUGHTFULLY COLLECTED &nbsp; / &nbsp; 01</div></article>`;}
function thumb(){return '<div class="doc-thumb" aria-hidden="true"></div>';}
function btn(label,action,cls='btn',extra=''){return `<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;}
function ib(name,action,label,extra=''){const cls=extra.match(/class="([^"]*)"/)?.[1]||'icon-btn';return btn(icon(name),action,cls,`aria-label="${label}" title="${label}" ${extra.replace(/class="[^"]*"/g,'')}`);}
function title(name,sub='',back='library',right=''){return `<header class="app-title"><div class="title-side">${back?ib('back','go:'+back,'Back'):''}<div><h2>${name}</h2>${sub?`<small>${sub}</small>`:''}</div></div>${right}</header>`;}
function nav(active){return `<nav class="bottom-nav" aria-label="App navigation">${[['library','folder','Library'],['capture','scan','Scan'],['tools','tools','Tools'],['settings','settings','Settings']].map(([s,i,l])=>btn(icon(i)+l,'go:'+s,s===active?'active':'',`aria-label="${l}"`)).join('')}</nav>`;}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3200);}
function sheet(content){lastFocus=document.activeElement;$('#modal').innerHTML=`<section class="sheet" role="dialog" aria-modal="true" aria-label="Prototype dialog">${content}</section>`;$('#modal').hidden=false;$('#app').inert=true;setTimeout(()=>$('#modal button, #modal textarea, #modal input')?.focus(),0);}
function closeSheet(){clearInterval(timer);timer=null;$('#modal').hidden=true;$('#modal').innerHTML='';$('#app').inert=false;if(lastFocus?.isConnected)lastFocus.focus();}
function go(screen){if(!screens.some(s=>s[0]===screen))screen='library';closeSheet();state.screen=screen;location.hash=screen;render();}
function libraryList(){const docs=state.docs.filter(d=>(state.folder==='All'||d.folder===state.folder)&&d.title.toLowerCase().includes(state.query.toLowerCase()));return docs.length?docs.map(d=>`<button class="doc-row" data-action="open-doc" data-title="${esc(d.title)}">${thumb()}<span><strong>${esc(d.title)}</strong><small>${d.pages} pages · ${d.date}</small></span>${icon('next')}</button>`).join(''):'<div class="empty"><h3>No matching documents</h3><p>Try another title or folder.</p></div>';}
function library(){return `${title('LumaScan','A little less paper.',null,ib('settings','go:settings','Settings','class="icon-btn soft"'))}<div class="screen-scroll"><h2 class="greeting">Your paper,<br>organized.</h2><label class="search">${icon('search')}<input id="library-search" aria-label="Search documents" placeholder="Search your documents" value="${esc(state.query)}"></label><button class="hero-scan" data-action="go:capture"><span><strong>Make a new scan</strong><small>One page or a whole new chapter.</small></span><span class="scan-graphic">${icon('scan')}</span></button><div class="quick-row">${btn(icon('import')+'Import','import','')}${btn(icon('id')+'ID copy','go:id','')}${btn(icon('video')+'Video scan','go:video','')}</div><div class="chips">${['All','Work','Personal','IDs'].map(f=>btn(f,'folder:'+f,'chip'+(state.folder===f?' selected':''),`aria-pressed="${state.folder===f}"`)).join('')}</div><h3 class="section-title">Recent documents <span>On this device</span></h3><div id="library-list">${libraryList()}</div></div>${nav('library')}`;}
function capture(){return `<div class="camera-screen"><div class="camera-top">${ib('close','go:library','Close camera')}${btn(state.auto?'Auto capture on':'Manual capture','auto','chip')}${ib('flash','flash',state.flash?'Turn flash off':'Turn flash on',`aria-pressed="${state.flash}"`)}</div><div class="viewfinder"><span class="camera-guidance">${state.captured?'Page added. Ready for the next one.':'Good light. Hold your page steady.'}</span>${paper()}<span class="sample-label">SIMULATED CAMERA PREVIEW</span></div><div class="mode-row">${btn('Document','mode:document','selected')}${btn('ID card','go:id','')}${btn('Photo','go:photo','')}${btn('Video','go:video','')}</div><div class="shutter-row">${btn(`${state.captured} pages`,'preview-capture','photo-count')}${btn(icon('camera'),'shutter','shutter','aria-label="Capture sample page"')}${btn('Done '+icon('next'),'capture-done','camera-text-btn',state.captured?'':'disabled')}</div><div class="camera-help">${state.auto?'Automatic capture · sample shutter enabled':'Manual capture'}${state.flash?' · Flash on':''}</div></div>`;}
function crop(){return `${title('Adjust corners','Page 1 · original preserved','capture',btn('Reset','reset-crop','inline-text-btn'))}<div class="screen-scroll"><div class="paper-stage crop-stage" id="crop-stage">${paper()}<svg class="crop-overlay" viewBox="0 0 100 100" preserveAspectRatio="none"><polygon id="crop-polygon" points=""/></svg>${state.crop.map((p,i)=>`<button class="crop-handle ${state.corner===i?'selected':''}" data-corner="${i}" aria-label="${['Top left','Top right','Bottom right','Bottom left'][i]} crop corner" aria-pressed="${state.corner===i}" style="left:${p[0]*100}%;top:${p[1]*100}%"></button>`).join('')}</div><p class="muted">Drag the corners to the paper edge, or select a corner and use the arrows.</p><div class="crop-controls">${btn('←','nudge:left','','aria-label="Move selected corner left"')}${btn('↑','nudge:up','','aria-label="Move selected corner up"')}${btn('↓','nudge:down','','aria-label="Move selected corner down"')}${btn('→','nudge:right','','aria-label="Move selected corner right"')}${btn(icon('rotate'),'rotate-crop','','aria-label="Rotate page"')}</div><div class="warning">Sample geometry only. Perspective correction runs in the native app.</div></div><div class="action-footer">${btn('Apply crop '+icon('next'),'go:filters','btn full')}</div>`;}
const filterNames=['Original','Auto','Clean Color','Grayscale','B&W','B&W Soft','High Contrast','Whiteboard'];
const cssFilters={'Original':'none','Auto':'contrast(1.12) brightness(1.04)','Clean Color':'contrast(1.2) brightness(1.09) saturate(.6)','Grayscale':'grayscale(1)','B&W':'grayscale(1) contrast(2.7)','B&W Soft':'grayscale(1) contrast(1.6) brightness(1.1)','High Contrast':'contrast(1.8)','Whiteboard':'contrast(1.25) brightness(1.2) saturate(1.2)'};
function filterStrip(names,selected,action){return `<div class="filter-strip">${names.map(f=>btn(`<span class="mini-paper"><i style="filter:${cssFilters[f]||'none'}"></i></span>${f}`,action+':'+f,'filter-card'+(selected===f?' selected':''),`aria-pressed="${selected===f}"`)).join('')}</div>`;}
function filters(){return `${title('Enhance','Find your kind of clear.','crop',btn(state.before?'Show edit':'Original','before','inline-text-btn'))}<div class="screen-scroll"><div class="paper-stage" id="filter-stage">${paper()}</div><div class="row"><span class="filter-preset-label">${state.before?'Original preview':state.filter}</span><span class="small-tag">REVERSIBLE EDITS</span></div>${filterStrip(filterNames,state.filter,'filter')}<label class="field">Strength <span id="strength-value">${state.strength}%</span><input type="range" id="strength" min="0" max="100" value="${state.strength}" ${state.filter==='Original'?'disabled':''}></label><label class="toggle-row">Apply enhancement to all pages<input id="apply-all" type="checkbox" ${state.applyAll?'checked':''}></label></div><div class="action-footer">${btn('Save enhancement '+icon('check'),'save-filter','btn full')}</div>`;}
function idMini(side){if(state.idSwapped)side=side==='front'?'back':'front';return `<div class="id-mini"><strong>EXAMPLE / ${side.toUpperCase()}</strong>${side==='front'?'<span class="id-portrait"></span>':''}<small>JAMIE SAMPLE<br>NOT A VALID DOCUMENT</small></div>`;}
function idScreen(){const two=state.template==='Card front & back';return `${title('ID copy','A guided copy, front to back.','capture')}<div class="screen-scroll"><label class="field">Document type<select id="id-template">${['Card front & back','Single-sided card','Passport page'].map(v=>`<option ${state.template===v?'selected':''}>${v}</option>`).join('')}</select></label><div class="id-slots" style="${two?'':'grid-template-columns:1fr'}">${btn(state.front?idMini('front')+'Retake '+(two?'front':'page'):icon('camera')+'Capture '+(two?'front':'page'),'id-front','id-slot'+(state.front?' captured':''))}${two?btn(state.back?idMini('back')+'Retake back':icon('plus')+'Capture back','id-back','id-slot'+(state.back?' captured':''),' '+(state.front?'':'disabled')):''}</div>${two?btn('Swap front and back','id-swap','inline-text-btn',state.front&&state.back?'':'disabled'):''}<h3 class="section-title">Copy layout <span>${esc(state.paper)} · fit to page</span></h3><div class="id-preview">${state.front?idMini('front'):'<span class="muted">Your copy preview appears here</span>'}${two&&state.back?idMini('back'):''}<span class="watermark" id="watermark-preview">${esc(state.watermark)}</span></div><label class="field">Copy-purpose watermark · optional<input id="watermark" maxlength="60" placeholder="e.g. For application only" value="${esc(state.watermark)}"></label><p class="muted">Creates a document copy. Does not verify identity.</p></div><div class="action-footer">${btn('Use this layout '+icon('next'),'id-save','btn full',state.front&&(!two||state.back)?'':'disabled')}</div>`;}
function video(){return `${title('Video to pages','Find the sharp moments.','capture',ib('import','video-import','Import sample video'))}<div class="screen-scroll"><div class="video-banner">${paper()}<span class="play-circle">${icon('play')}</span><span class="timecode">Sample clip · 00:24</span></div><div class="timeline" aria-label="Sample interval from 0 to 24 seconds"></div><div class="row muted"><span>00:00</span><span>Selected interval · 24 sec</span><span>00:24</span></div><h3 class="section-title">Suggested pages <span>${state.selectedFrames.size} selected</span></h3><div class="candidate-grid">${Array.from({length:6},(_,i)=>btn(`<span class="tick">${state.selectedFrames.has(i)?'✓':''}</span>${thumb()}<small>00:${String(state.replaced&&i===2?10:i*4+2).padStart(2,'0')} · ${i===2&&!state.replaced?'Blur':'Clear'}</small>`,'frame:'+i,'candidate'+(state.selectedFrames.has(i)?' selected':'')+(i===2&&!state.replaced?' warn':''),`aria-label="${state.selectedFrames.has(i)?'Deselect':'Select'} candidate ${i+1}" aria-pressed="${state.selectedFrames.has(i)}"`)).join('')}</div><div class="row">${btn('Analyze sample','analyze-video','inline-text-btn')}${btn('Replace blurry frame','replace-frame','inline-text-btn')}</div><p class="muted">Similar pages need a quick review. You decide what stays.</p></div><div class="action-footer">${btn(`Create ${state.selectedFrames.size} pages `+icon('next'),'video-save','btn full',state.selectedFrames.size?'':'disabled')}</div>`;}
function ocr(){return `${title('Extract text','Review before you reuse.','pages',btn('Copy','copy-text','inline-text-btn'))}<div class="screen-scroll"><div class="ocr-source">${thumb()}<div><strong>Field notes · Page 1</strong><span class="small-tag">REVIEW TEXT</span></div></div><label class="field">Recognition language<select id="ocr-language"><option>English · on-device</option></select></label><label class="field">Extracted text<textarea id="transcript" spellcheck="true">${esc(state.transcript)}</textarea></label><p class="muted">Corrections update this transcript. Your scanned image stays the same.</p><div class="warning">Sample transcript. This prototype does not run OCR.</div></div><div class="action-footer">${btn('Save corrections '+icon('check'),'save-text','btn full')}</div>`;}
function pages(){return `${title(esc(state.filename),`${state.pages.length} pages · ${esc(state.filterSaved)}`,'library',ib('plus','go:capture','Add pages'))}<div class="screen-scroll">${state.pages.length?state.pages.map((p,i)=>`<article class="page-card"><div style="transform:rotate(${p.rotation}deg)">${thumb()}</div><div class="page-card-body"><strong>${i+1}. ${esc(p.name)}</strong><small>Original kept · editable</small><div class="page-actions">${ib('up','page-up:'+i,'Move page '+(i+1)+' up',i===0?'disabled':'')}${ib('down','page-down:'+i,'Move page '+(i+1)+' down',i===state.pages.length-1?'disabled':'')}${ib('rotate','page-rotate:'+i,'Rotate page '+(i+1))}${ib('copy','page-copy:'+i,'Duplicate page '+(i+1))}${ib('trash','page-delete:'+i,'Delete page '+(i+1))}</div>${p.note?`<div class="annotation-badge">${esc(p.note)}</div>`:''}</div></article>`).join(''):'<div class="empty"><h3>No pages yet</h3><p>Add a scan to start this document.</p></div>'}<div class="row">${btn(icon('plus')+'Add pages','go:capture','btn outline')}${btn(icon('edit')+'Annotate','annotate','btn outline',state.pages.length?'':'disabled')}</div>${state.undoPages?btn('Undo page deletion','undo-page','inline-text-btn'):''}<p class="muted">Move pages with the arrows. Changes carry through to your export.</p></div><div class="action-footer"><div class="row">${btn(icon('text')+'Extract text','go:ocr','btn secondary',state.pages.length?'':'disabled')}${btn(icon('share')+'Export','go:export','btn',state.pages.length?'':'disabled')}</div></div>`;}
function exportScreen(){return `${title('Export document','A little file. A lot of possibility.','pages')}<div class="screen-scroll"><label class="field">File name<input id="filename" value="${esc(state.filename)}" maxlength="80"></label><label class="field">Format</label><div class="format-row">${['PDF','Images','TXT'].map(f=>btn(f,'format:'+f,state.format===f?'selected':'',`aria-pressed="${state.format===f}"`)).join('')}</div>${state.format==='PDF'?`<label class="field">Paper size<select id="paper">${['A4','Letter','Fit to image'].map(v=>`<option ${state.paper===v?'selected':''}>${v}</option>`).join('')}</select></label><label class="toggle-row">Make text searchable<input type="checkbox" id="searchable" ${state.searchable?'checked':''}></label>`:''}${state.format!=='TXT'?`<label class="field">Quality</label><div class="quality-row">${['Compact','Balanced','Print'].map(v=>btn(v,'quality:'+v,state.quality===v?'selected':'',`aria-pressed="${state.quality===v}"`)).join('')}</div>`:'<p class="muted">Exports the reviewed transcript. Layout and images are not included.</p>'}<div class="export-summary">${icon('file')}<div><strong>${state.pages.length} pages · ${state.format}</strong><small>Sample estimate · ${state.format==='TXT'?'2 KB':state.quality==='Compact'?'640 KB':state.quality==='Print'?'4.8 MB':'1.6 MB'}</small></div></div><p class="muted">Keep your original scans. Create a new file for sharing.</p><p class="simulate-label">EXPORT IS SIMULATED IN THIS DESIGN</p></div><div class="action-footer">${btn('Export '+state.format+' '+icon('share'),'export','btn full',state.pages.length?'':'disabled')}</div>`;}
function photoArt(){return `<svg class="photo-art" id="photo-art" viewBox="0 0 340 290" role="img" aria-label="Sample illustration of a sunlit desk with a plant and a cup"><defs><linearGradient id="wall" x2="1" y2="1"><stop stop-color="#e2d3b4"/><stop offset="1" stop-color="#baa77e"/></linearGradient><linearGradient id="table" x2="0" y2="1"><stop stop-color="#b6824c"/><stop offset="1" stop-color="#946134"/></linearGradient></defs><path fill="url(#wall)" d="M0 0h340v220H0z"/><path fill="#f4e9c9" opacity=".65" d="M20 0h78l146 220H149zM116 0h43l146 220h-52z"/><path fill="#a69166" d="M0 212h340v7H0z"/><path fill="url(#table)" d="M0 219h340v71H0z"/><ellipse cx="120" cy="250" rx="83" ry="13" fill="#543b23" opacity=".18"/><ellipse cx="252" cy="247" rx="40" ry="8" fill="#513d29" opacity=".2"/><path d="M77 186h70l-9 58H87z" fill="#d4b38c"/><path d="M78 187h69v9H78z" fill="#e6c69d"/><path d="M111 190c-8-53 3-87 12-134M112 154c-33-2-54-29-56-49M117 122c34-9 53-27 61-49" fill="none" stroke="#4d6940" stroke-width="4"/><path d="M113 166C66 176 51 143 46 127c40-8 63 8 67 39M119 139c2-39 31-51 57-46-5 31-29 45-57 46M120 103c-30-6-40-29-39-50 30 2 43 24 39 50M124 76c-2-32 16-48 35-51 8 28-8 44-35 51" fill="#526f40"/><path d="M229 213h43v28q-20 13-43 0z" fill="#f7ead1"/><ellipse cx="250" cy="213" rx="22" ry="6" fill="#eee1c6"/><ellipse cx="250" cy="213" rx="16" ry="3" fill="#785133"/><path d="M273 217c23-2 20 24-1 19" fill="none" stroke="#f7ead1" stroke-width="7"/><path d="M156 253l42-14 34 15-40 17z" fill="#d9dcc6"/><path d="M158 250l41-14 34 16-40 15z" fill="#f2ebd5"/></svg>`;}
function photo(){return `${title('Photo studio','A fresh point of view.','capture',btn(state.photoBefore?'Show edit':'Original','photo-before','inline-text-btn'))}<div class="screen-scroll"><div class="photo-wrap">${photoArt()}<span class="small-tag">${state.photoBefore?'ORIGINAL':'SAMPLE ILLUSTRATION'}</span></div><div class="chips">${['Natural','Vivid','Warm','Cool','Mono'].map(f=>btn(f,'photo-style:'+f,'chip'+(state.photoStyle===f?' selected':''),`aria-pressed="${state.photoStyle===f}"`)).join('')}</div><label class="slider-label" for="exposure">Exposure <span id="exposure-value">${state.exposure}</span></label><input type="range" id="exposure" min="-50" max="50" value="${state.exposure}"><label class="slider-label" for="saturation">Saturation <span id="saturation-value">${state.saturation}</span></label><input type="range" id="saturation" min="0" max="200" value="${state.saturation}">${btn('Reset adjustments','photo-reset','inline-text-btn')}</div><div class="action-footer">${btn('Save a copy '+icon('check'),'photo-save','btn full')}</div>`;}
function toolsScreen(){const current=[['scan','Scan document','Quick, clean pages','go:capture'],['id','ID copy','Front and back','go:id'],['photo','Photo studio','Color and light','go:photo'],['text','Extract text','Editable transcript','go:ocr'],['file','Organize PDF','Put pages in order','go:pages'],['video','Video scan','Choose the best frames','go:video']];const planned=[['copy','Merge & split','PDF tools · R1.1'],['lock','Protect PDF','Password export · R1.1'],['video','Photos to video','Media tools · R2'],['scan','3D capture','Device research · R4']];return `${title('Your toolkit','Small tools. Useful possibilities.',null)}<div class="screen-scroll"><h3 class="section-title">Capture & create</h3><div class="tool-grid">${current.map(([i,t,s,a])=>btn(icon(i)+`<strong>${t}</strong><small>${s}</small>`,a,'tool-tile')).join('')}</div><h3 class="section-title">Coming in later releases</h3><div class="tool-grid">${planned.map(([i,t,s])=>btn(icon(i)+`<strong>${t}</strong><small>${s}</small>`,'planned:'+t,'tool-tile planned')).join('')}</div></div>${nav('tools')}`;}
function settings(){return `${title('Settings','Make it yours.',null)}<div class="screen-scroll"><div class="panel"><h3>${icon('lock')} On your device</h3><p>Your scans stay local. No account needed for capture, editing or export.</p></div><h3 class="section-title">Document defaults</h3><div class="panel"><label class="field">Paper size<select id="paper">${['A4','Letter','Fit to image'].map(v=>`<option ${state.paper===v?'selected':''}>${v}</option>`).join('')}</select></label><label class="field">Export quality<select id="default-quality">${['Compact','Balanced','Print'].map(v=>`<option ${state.quality===v?'selected':''}>${v}</option>`).join('')}</select></label></div><h3 class="section-title">Storage & permissions</h3><div class="panel">${btn('<span>English OCR model</span><small>'+ (state.modelReady?'Ready · sample':'Not installed')+'</small>','error:model','settings-row')}${btn('<span>Local storage</span><small>42 MB · sample</small>','error:storage','settings-row')}${btn('<span>Camera permission</span>'+icon('next'),'error:camera','settings-row')}</div><div class="panel"><h3>Planned privacy options</h3><p>Biometric lock and optional backup require separate implementation.</p></div><p class="muted">Prototype settings last for this browser session. No real files or device permissions are changed.</p></div>${nav('settings')}`;}
const views={library,capture,crop,filters,id:idScreen,video,ocr,pages,export:exportScreen,photo,tools:toolsScreen,settings};
function render(){const screen=screens.find(s=>s[0]===state.screen);$('#screen-nav').innerHTML=screens.map((s,i)=>`<a class="screen-link${s[0]===state.screen?' active':''}" href="#${s[0]}" ${s[0]===state.screen?'aria-current="page"':''}><span>${String(i+1).padStart(2,'0')}</span>${s[1]}</a>`).join('');$('#note-number').textContent=String(screens.indexOf(screen)+1).padStart(2,'0');$('#note-category').textContent=screen[2];$('#note-title').textContent=screen[3];$('#note-description').textContent=screen[4];$('#note-actions').innerHTML=screen[5].map(t=>`<li>${t}</li>`).join('');$('#app').innerHTML=views[state.screen]();if(state.screen==='crop')paintCrop();if(state.screen==='filters')paintFilter();if(state.screen==='photo')paintPhoto();}
function paintFilter(){const el=$('#filter-stage .paper');if(!el)return;const amount=state.strength/100;const f=state.filter;let value=cssFilters[f];if(f==='Clean Color')value=`contrast(${1+.2*amount}) brightness(${1+.09*amount}) saturate(${1-.4*amount})`;else if(f==='Auto')value=`contrast(${1+.12*amount}) brightness(${1+.04*amount})`;else if(f==='Grayscale')value=`grayscale(${amount})`;else if(f==='B&W'||f==='B&W Soft')value=`grayscale(${amount}) contrast(${1+(f==='B&W'?1.7:.6)*amount})`;else if(f==='High Contrast')value=`contrast(${1+.8*amount})`;else if(f==='Whiteboard')value=`contrast(${1+.25*amount}) brightness(${1+.2*amount})`;el.style.filter=state.before?'none':value;}
function paintPhoto(){const el=$('#photo-art');if(!el)return;const presets={Natural:'',Vivid:'contrast(1.15) saturate(1.3)',Warm:'sepia(.23) saturate(1.1)',Cool:'hue-rotate(18deg) saturate(.8)',Mono:'grayscale(1)'};el.style.filter=state.photoBefore?'none':`brightness(${1+state.exposure/100}) saturate(${state.saturation/100}) ${presets[state.photoStyle]}`;}
function validQuad(points){let sign=0;for(let i=0;i<4;i++){const a=points[i],b=points[(i+1)%4],c=points[(i+2)%4];const cross=(b[0]-a[0])*(c[1]-b[1])-(b[1]-a[1])*(c[0]-b[0]);if(Math.abs(cross)<.015)return false;const s=Math.sign(cross);if(sign&&sign!==s)return false;sign=s;}return true;}
function moveCorner(x,y){const next=state.crop.map(p=>[...p]);next[state.corner]=[Math.max(.04,Math.min(.96,x)),Math.max(.04,Math.min(.96,y))];if(validQuad(next)){state.crop=next;paintCrop();}}
function paintCrop(){const poly=$('#crop-polygon');if(!poly)return;poly.setAttribute('points',state.crop.map(p=>p.map(v=>v*100).join(',')).join(' '));document.querySelectorAll('.crop-handle').forEach((b,i)=>{b.style.left=state.crop[i][0]*100+'%';b.style.top=state.crop[i][1]*100+'%';b.classList.toggle('selected',state.corner===i);b.setAttribute('aria-pressed',String(state.corner===i));});$('#crop-stage .paper').style.transform=`rotate(${state.rotation}deg) scale(${state.rotation%180?.75:1})`;}
function simulatedJob(kind,onDone){sheet(`<h3>${kind==='export'?'Preparing your file':'Finding clear pages'}</h3><p>Simulated ${kind==='export'?'export':'video analysis'} for screen review.</p><div class="progress-track" role="progressbar" aria-label="Simulation progress" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-fill"></div></div><p id="job-progress">Starting…</p>${btn('Cancel','cancel-job','btn secondary full')}`);let progress=0;timer=setInterval(()=>{progress+=10;$('.progress-fill').style.width=progress+'%';$('.progress-track').setAttribute('aria-valuenow',progress);$('#job-progress').textContent=progress+'% · '+(kind==='export'?'Building sample output':'Reviewing sample frames');if(progress>=100){clearInterval(timer);timer=null;onDone();}},170);}
function errorSheet(kind){const content={camera:['Camera access is off','You can still import a photo. In the real app, Open settings takes you to the system permission screen.','Open settings','sample-settings'],storage:['Not enough storage','Your saved pages are safe. Free space before trying the export again. This is an example error state.','Manage storage','sample-storage'],model:['Text model needed','Download the English model before recognizing text offline. This is an example model state.','Download sample model','sample-model']}[kind];sheet(`<h3>${content[0]}</h3><p>${content[1]}</p>${btn(content[2],content[3],'btn full')}${kind==='camera'?btn('Import sample instead','import','btn outline full'):''}${btn('Close','close','btn secondary full')}`);}
document.addEventListener('click',async event=>{
  const target=event.target.closest('[data-action]');if(!target||target.disabled)return;
  const [action,...parts]=target.dataset.action.split(':');const value=parts.join(':');
  if(action==='go'){if(value==='capture'&&state.screen==='library'){state.captured=0;state.filename='Untitled scan';state.pages=[];}go(value);return;}if(action==='close'){closeSheet();return;}
  if(action==='folder'){state.folder=value;render();return;}
  if(action==='import'){closeSheet();state.docs.unshift({title:'Imported sample page',pages:1,date:'Just now',folder:'Personal'});go('library');toast('Fictional sample added. No file was imported.');return;}
  if(action==='open-doc'){state.filename=target.dataset.title;const doc=state.docs.find(d=>d.title===state.filename);state.pages=Array.from({length:doc?.pages||1},(_,i)=>({id:state.nextId++,name:state.filename+' · '+(i+1),rotation:0}));go('pages');return;}
  if(action==='auto'){state.auto=!state.auto;render();return;}if(action==='flash'){state.flash=!state.flash;render();return;}
  if(action==='mode'){toast('Document mode selected.');return;}
  if(action==='shutter'){state.captured++;state.pages.push({id:state.nextId++,name:'New scan '+state.captured,rotation:0});render();toast('Sample page captured.');return;}
  if(action==='capture-done'){go('crop');return;}
  if(action==='preview-capture'){if(state.captured)go('pages');else toast('Capture a sample page first.');return;}
  if(action==='reset-crop'){state.crop=[[.17,.08],[.83,.08],[.83,.92],[.17,.92]];state.rotation=0;paintCrop();return;}
  if(action==='nudge'){const [x,y]=state.crop[state.corner];moveCorner(x+(value==='left'?-.02:value==='right'?.02:0),y+(value==='up'?-.02:value==='down'?.02:0));return;}
  if(action==='rotate-crop'){state.rotation=(state.rotation+90)%360;paintCrop();return;}
  if(action==='filter'){state.filter=value;state.before=false;render();return;}
  if(action==='before'){state.before=!state.before;render();return;}
  if(action==='save-filter'){state.filterSaved=state.filter;go('pages');toast(state.applyAll?'Sample enhancement applied to all pages.':'Sample page enhancement saved.');return;}
  if(action==='id-front'||action==='id-back'){state[action==='id-front'?'front':'back']=true;render();toast('Fictional '+(action==='id-front'?'front':'back')+' captured.');return;}
  if(action==='id-swap'){state.idSwapped=!state.idSwapped;render();toast('Sample front/back slots swapped.');return;}
  if(action==='id-save'){state.filename='ID copy · sample';state.pages=[{id:state.nextId++,name:'ID layout · '+state.template,rotation:0,note:state.watermark}];go('pages');return;}
  if(action==='frame'){const i=Number(value);state.selectedFrames.has(i)?state.selectedFrames.delete(i):state.selectedFrames.add(i);render();return;}
  if(action==='video-import'){toast('Sample 24-second clip loaded. No real video imported.');return;}
  if(action==='analyze-video'){simulatedJob('video',()=>{closeSheet();state.videoAnalyzed=true;render();toast('Sample analysis ready: review 6 candidates.');});return;}
  if(action==='replace-frame'){state.replaced=!state.replaced;render();toast(state.replaced?'Replaced with a neighboring sample frame.':'Original sample frame restored.');return;}
  if(action==='video-save'){state.filename='Video scan · sample';state.pages=[...state.selectedFrames].sort((a,b)=>a-b).map(i=>({id:state.nextId++,name:'Frame at 00:'+String(state.replaced&&i===2?10:i*4+2).padStart(2,'0'),rotation:0}));go('pages');return;}
  if(action==='save-text'){state.transcript=$('#transcript').value;toast('Sample transcript corrections saved.');return;}
  if(action==='copy-text'){state.transcript=$('#transcript').value;try{if(!navigator.clipboard?.writeText)throw new Error('Clipboard unavailable');await navigator.clipboard.writeText(state.transcript);toast('Transcript copied.');}catch{toast('Clipboard unavailable here. Select the text and copy manually.');}return;}
  if(action.startsWith('page-')){const i=Number(value);if(action==='page-up'&&i>0)[state.pages[i-1],state.pages[i]]=[state.pages[i],state.pages[i-1]];if(action==='page-down'&&i<state.pages.length-1)[state.pages[i+1],state.pages[i]]=[state.pages[i],state.pages[i+1]];if(action==='page-rotate')state.pages[i].rotation=(state.pages[i].rotation+90)%360;if(action==='page-copy')state.pages.splice(i+1,0,{...state.pages[i],id:state.nextId++,name:state.pages[i].name+' copy'});if(action==='page-delete'){state.undoPages=state.pages.map(p=>({...p}));state.pages.splice(i,1);}render();return;}
  if(action==='undo-page'){state.pages=state.undoPages;state.undoPages=null;render();return;}
  if(action==='annotate'){sheet(`<h3>Add a text note</h3><p>Sample annotation on the first page. The product also plans ink, highlight and signature tools.</p><textarea id="annotation" aria-label="Page annotation" maxlength="160" placeholder="Add a note…">${esc(state.pages[0]?.note||'')}</textarea>${btn('Save note','save-note','btn full')}${btn('Cancel','close','btn secondary full')}`);return;}
  if(action==='save-note'){state.pages[0].note=$('#annotation').value;closeSheet();render();return;}
  if(action==='format'){state.format=value;render();return;}
  if(action==='quality'){state.quality=value;render();return;}
  if(action==='export'){simulatedJob('export',()=>{sheet(`<div class="complete-icon">${icon('check')}</div><h3>Export preview complete</h3><p>${esc(state.filename)} · ${state.format}</p><p>This was a simulation. No PDF, image or text file was generated. The native app will offer Save and Share here.</p>${btn('Back to document','go:pages','btn full')}${btn('Close','close','btn secondary full')}`);});return;}
  if(action==='cancel-job'){closeSheet();toast('Simulation cancelled. Your sample pages are safe.');return;}
  if(action==='photo-style'){state.photoStyle=value;state.photoBefore=false;render();return;}
  if(action==='photo-before'){state.photoBefore=!state.photoBefore;render();return;}
  if(action==='photo-reset'){state.photoStyle='Natural';state.exposure=0;state.saturation=100;state.photoBefore=false;render();return;}
  if(action==='photo-save'){go('library');toast('Photo save previewed. No image file was generated.');return;}
  if(action==='planned'){sheet(`<h3>${esc(value)}</h3><p>This feature is planned for a later release. ${value==='3D capture'?'Depth capture, reconstruction and device support need a separate prototype.':'Its native processing and export behavior are specified in the roadmap.'}</p>${btn('Got it','close','btn full')}`);return;}
  if(action==='error'){errorSheet(value);return;}
  if(action==='sample-settings'){closeSheet();toast('In the native app, this opens system permissions.');return;}
  if(action==='sample-storage'){closeSheet();toast('Storage management preview only. No files changed.');return;}
  if(action==='sample-model'){state.modelReady=true;closeSheet();render();toast('Model download simulated. No network request made.');}
});
document.addEventListener('input',event=>{const e=event.target;switch(e.id){case'library-search':state.query=e.value;$('#library-list').innerHTML=libraryList();break;case'strength':state.strength=Number(e.value);$('#strength-value').textContent=e.value+'%';paintFilter();break;case'watermark':state.watermark=e.value;$('#watermark-preview').textContent=e.value;break;case'transcript':state.transcript=e.value;break;case'filename':state.filename=e.value.replace(/[\\/:*?"<>|]/g,'').trim()||'Untitled scan';break;case'exposure':state.exposure=Number(e.value);$('#exposure-value').textContent=e.value;paintPhoto();break;case'saturation':state.saturation=Number(e.value);$('#saturation-value').textContent=e.value;paintPhoto();break;}});
document.addEventListener('change',event=>{const e=event.target;if(e.id==='id-template'){state.template=e.value;render();}if(e.id==='apply-all')state.applyAll=e.checked;if(e.id==='searchable')state.searchable=e.checked;if(e.id==='paper')state.paper=e.value;if(e.id==='default-quality')state.quality=e.value;});
let drag=null;
document.addEventListener('pointerdown',e=>{const h=e.target.closest('[data-corner]');if(!h)return;state.corner=Number(h.dataset.corner);paintCrop();drag={pointerId:e.pointerId,rect:$('#crop-stage').getBoundingClientRect(),target:h};h.setPointerCapture(e.pointerId);});
document.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.pointerId)return;moveCorner((e.clientX-drag.rect.left)/drag.rect.width,(e.clientY-drag.rect.top)/drag.rect.height);});
document.addEventListener('pointerup',()=>{drag=null;});document.addEventListener('pointercancel',()=>{drag=null;});
document.addEventListener('keydown',e=>{if(!$('#modal').hidden){if(e.key==='Escape'){e.preventDefault();closeSheet();return;}if(e.key==='Tab'){const nodes=[...$('#modal').querySelectorAll('button:not(:disabled),input,textarea,select,a[href]')];const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}const h=e.target.closest?.('[data-corner]');if(h&&['Enter',' '].includes(e.key)){e.preventDefault();state.corner=Number(h.dataset.corner);paintCrop();}});
window.addEventListener('hashchange',()=>{const route=location.hash.slice(1);if(route!==state.screen)go(route);});
go(location.hash.slice(1)||'library');
