'use strict';
const asset = name => `assets/${name}.svg`;
const screens = [
  {id:'library',name:'Library',purpose:'Start a scan',note:'Library entry',copy:'Start with New scan. Every visible primary action is clickable.'},
  {id:'camera',name:'Camera preview',purpose:'Capture pages',note:'Capture controls',copy:'Toggle Batch, Flash and Auto. Open settings for Grid and synchronized controls.'},
  {id:'select',name:'Document editor',purpose:'Re-edit draft or saved pages',note:'Persistent edit access',copy:'Drafts and saved documents reopen with Crop and Filter available on every page.'},
  {id:'actions',name:'Batch actions',purpose:'Choose an operation',note:'Contextual sheet',copy:'The action sheet preserves selection context and keeps editing out of the camera.'},
  {id:'crop',name:'Crop & resize',purpose:'Readjust page boundaries',note:'Recoverable geometry',copy:'Drag any corner, rotate, reset to detected edges, or restore the full original image.'},
  {id:'enhance',name:'Filters',purpose:'Preview and apply',note:'Non-destructive preview',copy:'Switch presets at any time, even after save. The original source remains untouched.'},
  {id:'organize',name:'Organize',purpose:'Reorder safely',note:'Page organization',copy:'Select a row, move it, duplicate it or delete with confirmation.'},
  {id:'export',name:'Export',purpose:'Configure output',note:'Export configuration',copy:'Choose format and quality, then watch real progress feedback.'},
  {id:'success',name:'Complete',purpose:'Share or save',note:'Completion state',copy:'The final state reports actual output and provides clear next actions.'}
];
const initialState=()=>({index:0,history:[],selected:new Set([0]),pageCount:4,documentName:'Untitled scan',documentStatus:'Draft · autosaved',draftSaved:false,cameraMode:'Docs',camera:{batch:true,flash:false,auto:true,grid:false},settings:false,photoPreview:false,confirmDiscard:false,filter:'Auto color',strength:72,cropPreset:'Detected edges',cropInset:12,format:'PDF',quality:'Recommended',ocr:true,processing:false,progress:0,organizePage:3,confirmDelete:false});
const state=initialState();
const root=document.querySelector('#prototype-screen');
const list=document.querySelector('#screen-list');
const eventLog=document.querySelector('#event-log');
const stateSummary=document.querySelector('#state-summary');
let progressTimer=null;

const object=()=>`<object data="${asset('document-preview')}" type="image/svg+xml" aria-label="Document page"></object>`;
const filterClass=name=>name.toLowerCase().replace(/[^a-z]+/g,'-');
const filterThumbnail=name=>`<span class="filter-thumb filter-${filterClass(name)}"><img loading="lazy" decoding="async" data-src="${asset('document-preview')}" alt="${name} filter preview"></span><span>${name}</span>`;
const nav=(title,right='')=>`<div class="screen-nav"><button data-back>‹ Back</button><b>${title}</b><button ${right?'':'disabled'} data-action="${right}">${right}</button></div>`;
const log=message=>{eventLog.textContent=message};
const go=(target,direction='forward')=>{if(typeof target==='string')target=screens.findIndex(s=>s.id===target);if(target<0||target>=screens.length)return;state.history.push(state.index);state.index=target;render(direction);};
const back=()=>{const target=state.history.length?state.history.pop():Math.max(0,state.index-1);state.index=target;render('back');};

function library(){return `<div class="welcome"><small>Good morning</small><h3>Your documents</h3></div><button class="big-action" data-go="camera"><i>⌗</i><span><b>New scan</b><small>Camera · auto edges · multi-page</small></span><em>›</em></button><button class="draft-card" data-open-document="draft"><span><b>Continue draft</b><small>4 pages · autosaved · tap to edit</small></span><em>Resume ›</em></button><p class="label">QUICK ACTIONS</p><div class="quick"><button data-go="camera"><i>↑</i>Import</button><button data-go="camera"><i>▣</i>ID copy</button><button data-go="camera"><i>▶</i>Video</button></div><p class="label">RECENT</p><button class="recent" data-open-document="saved" data-name="Algebra notes">${object()}<span><b>Algebra notes</b><small>12 pages · Saved · editable</small></span><b>›</b></button><button class="recent" data-open-document="saved" data-name="Receipts">${object()}<span><b>Receipts</b><small>8 pages · Saved · editable</small></span><b>›</b></button>`}

function cameraSettings(){if(!state.settings)return'';return `<div class="modal-layer" data-close-settings><section class="bottom-sheet" onclick="event.stopPropagation()"><span class="grabber"></span><div class="sheet-head"><span><b>Camera settings</b><small>Capture options only</small></span><button data-close-settings>×</button></div>${setting('batch','▣','Batch mode','Keep capturing without review')}${setting('flash','⚡','Flashlight','Continuous light while scanning')}${setting('auto','◎','Auto capture','Capture when edges are stable')}${setting('grid','#','Alignment grid','Show a 3 × 3 guide')}<button class="setting" data-toast="More capture settings opened"><span><i>⚙</i><em><b>More capture settings</b><small>Resolution, shutter sound, save original</small></em></span><b>›</b></button></section></div>`}
function setting(key,icon,title,copy){return `<div class="setting"><span><i>${icon}</i><em><b>${title}</b><small>${copy}</small></em></span><button class="switch ${state.camera[key]?'on':''}" data-camera="${key}" aria-pressed="${state.camera[key]}"></button></div>`}
const captureModes=['Docs','Book','Text','OCR Doc','QR','Photo'];
function modeGuidance(){return {Docs:state.camera.auto?'Hold steady':'Tap shutter to capture',Book:'Align the book spine',Text:'Point at text to recognize','OCR Doc':'Fill the frame with the page',QR:'Place QR code in the frame',Photo:'Compose your photo'}[state.cameraMode]}
function modeOverlay(){if(state.cameraMode==='Book')return '<div class="book-guide"><span>LEFT PAGE</span><i></i><span>RIGHT PAGE</span></div>';if(state.cameraMode==='Text')return '<div class="text-guide"><i style="--x:12%;--y:21%;--w:68%"></i><i style="--x:18%;--y:38%;--w:61%"></i><i style="--x:14%;--y:56%;--w:70%"></i><b>Live text detected</b></div>';if(state.cameraMode==='OCR Doc')return '<div class="ocr-guide"><b>OCR</b><span>Image + searchable text layer</span></div>';if(state.cameraMode==='QR')return '<div class="qr-guide"><i></i><span>QR detected</span></div>';return ''}
function capturedPhotos(){if(!state.photoPreview)return'';const count=state.pageCount;return `<div class="modal-layer captured-preview"><section class="bottom-sheet"><span class="grabber"></span><div class="sheet-head"><span><b>Captured photos</b><small>${count} pages in this scan</small></span><button data-close-photos aria-label="Close captured photos">×</button></div><div class="captured-grid">${count?Array.from({length:Math.min(count,6)},(_,i)=>`<button data-photo-page="${i+1}" aria-label="Preview captured page ${i+1}">${object()}<i>${i+1}</i></button>`).join(''):'<p class="empty-captures">No captured photos yet.</p>'}</div><button class="primary" data-review-photos ${count?'':'disabled'}>Review all ${count} pages</button><button class="secondary" data-close-photos>Continue scanning</button></section></div>`}
function camera(){const c=state.camera;const discard=state.confirmDiscard?`<div class="modal-layer"><section class="confirm-card discard-card"><i>×</i><h3>Discard the photos?</h3><p>Are you sure you want to discard the photos? All captured photos and changes will be permanently removed and cannot be restored.</p><button class="danger-button" data-confirm-discard>Discard photos</button><button class="secondary" data-cancel-discard>Keep photos</button></section></div>`:'';return `<div class="camera ${c.flash?'flash':''} ${c.grid?'grid':''}"><object data="${asset('camera-document')}" type="image/svg+xml" aria-label="Live ${state.cameraMode} preview"></object>${modeOverlay()}<div class="camera-flash" aria-hidden="true"></div><div class="camera-top"><span class="camera-top-spacer" aria-hidden="true"></span><span class="guide">${modeGuidance()}</span><button class="round" data-settings>•••</button></div><div class="camera-toggles">${cameraToggle('batch','▣','Batch')}${cameraToggle('flash','⚡','Flash')}${cameraToggle('auto','◎','Auto')}</div>${c.batch&&state.cameraMode!=='QR'?`<div class="camera-count"><b>${state.pageCount}</b>pages captured</div>`:''}<div class="camera-modes">${captureModes.map(mode=>`<button class="${state.cameraMode===mode?'active':''}" data-camera-mode="${mode}">${mode}</button>`).join('')}</div><div class="capture-controls"><button class="mini-thumb" data-open-photos aria-label="Open preview of ${state.pageCount} captured photos">${object()}<i>${state.pageCount}</i></button><button class="shutter" data-shutter aria-label="${state.cameraMode==='QR'?'Scan QR code':state.cameraMode==='Text'?'Capture recognized text':state.cameraMode==='Book'?'Capture left and right book pages':'Capture page'}"></button><button class="done camera-discard" data-discard-capture aria-label="Discard all captured photos and changes">×</button></div>${cameraSettings()}${capturedPhotos()}${discard}</div>`}
function cameraToggle(key,icon,title){return `<button class="camera-toggle ${state.camera[key]?'active':''}" data-camera="${key}" aria-pressed="${state.camera[key]}"><i>${icon}</i><span><b>${title}</b><small>${state.camera[key]?'On':'Off'}</small></span></button>`}

function select(){const pages=Array.from({length:6},(_,i)=>`<button class="page ${state.selected.has(i)?'selected':''}" data-page="${i}">${object()}${state.selected.has(i)?'<i>✓</i>':''}</button>`).join('');const disabled=state.selected.size?'':'disabled';return `${nav(state.documentName,'all')}<div class="document-status"><span><b>${state.documentStatus}</b><small>Originals retained · edits can be changed anytime</small></span><button data-toast="Document edit history opened">History</button></div><div class="pages">${pages}</div><div class="batchbar editorbar"><button ${disabled} data-go="crop"><i>⌗</i>Crop</button><button ${disabled} data-go="enhance"><i>◐</i>Filter</button><button ${disabled} data-action-sheet="rotate"><i>↻</i>Rotate</button><button ${disabled} data-action-sheet="organize"><i>↕</i>Pages</button><button ${disabled} data-action-sheet="more"><i>•••</i>More</button></div>`}

const actionData={enhance:['Enhance selected','Preview filters and contrast before applying.',['✦ Auto enhance','◐ Choose filter','⌁ Remove marks']],rotate:['Rotate selected','Apply one safe transform to the selection.',['↺ Rotate left','↻ Rotate right','⌗ Review crop']],organize:['Organize selected','Change order without losing pages.',['↕ Move pages','▣ Duplicate','⌫ Delete']],more:['More actions','Additional actions for selected pages.',['T Extract text','□ Export selected','••• Page details']]};
function actions(){const data=state.actionSheet||actionData.enhance;return `<div class="camera" style="filter:saturate(.5)"><div class="pages" style="opacity:.25">${Array.from({length:4},()=>`<div class="page">${object()}</div>`).join('')}</div></div><div class="modal-layer"><section class="bottom-sheet"><span class="grabber"></span><div class="sheet-head"><span><b>${data[0]}</b><small>${state.selected.size} selected pages</small></span><button data-back>×</button></div><p style="color:var(--muted);font-size:10px">${data[1]}</p>${data[2].map((item,i)=>`<button class="setting" data-choice="${i}"><span><i>${item.split(' ')[0]}</i><em><b>${item.substring(item.indexOf(' ')+1)}</b><small>Tap to continue</small></em></span><b>›</b></button>`).join('')}<button class="secondary" data-back>Cancel</button></section></div>`}

function crop(){return `${nav('Crop & resize','select')}<div class="crop-note"><b>${state.documentStatus.startsWith('Saved')?'Editing saved document':'Editing autosaved draft'}</b><span>Adjusting the crop never replaces the original photo.</span></div><div class="crop-preview">${object()}<div class="crop-quad" style="inset:${state.cropInset}%"><i></i><i></i><i></i><i></i></div></div><div class="crop-presets"><button class="${state.cropPreset==='Detected edges'?'active':''}" data-crop-preset="Detected edges">Detected edges</button><button class="${state.cropPreset==='Full image'?'active':''}" data-crop-preset="Full image">Full image</button></div><label class="range"><span>Crop area</span><b>${100-state.cropInset*2}%</b><input data-crop-inset type="range" min="2" max="22" value="${state.cropInset}"></label><div class="crop-actions"><button data-toast="Page rotated left">↺ Left</button><button data-toast="Page rotated right">↻ Right</button><button data-reset-crop>Reset</button></div><button class="primary" data-save-edit="crop">Save crop</button>`}
function enhance(){return `${nav('Filter','select')}<div class="edit-mode-note"><b>Re-editable</b><span>${state.documentStatus}; switch filters without recropping.</span></div><div class="edit-preview filter-${filterClass(state.filter)}">${object()}<span class="compare">↔</span></div><p class="label">DOCUMENT FILTER · EFFECT PREVIEW</p><div class="presets filter-presets">${['Original','Auto color','Enhanced color','Bright','Grayscale','B&W'].map(x=>`<button class="${state.filter===x?'active':''}" data-filter="${x}" aria-label="Preview and apply ${x} filter">${filterThumbnail(x)}</button>`).join('')}</div><label class="range"><span>Strength</span><b>${state.filter==='Original'?0:state.strength}%</b><input data-strength type="range" min="0" max="100" value="${state.strength}" ${state.filter==='Original'?'disabled':''}></label><div class="filter-actions"><button data-reset-filter>Reset filter</button><button data-toast="Hold preview to compare with original">Before / after</button></div><button class="primary" data-save-edit="filter">Save filter to ${state.selected.size} page${state.selected.size===1?'':'s'}</button>`}
function organize(){const confirm=state.confirmDelete?`<div class="modal-layer"><section class="confirm-card"><i>⌫</i><h3>Delete page ${state.organizePage}?</h3><p>You can undo this action for 8 seconds.</p><button class="danger-button" data-confirm-delete>Delete page</button><button class="secondary" data-cancel-delete>Cancel</button></section></div>`:'';return `${nav('Organize','export')}<p class="label">HOLD AND DRAG, OR USE MOVE</p><div class="organize">${[1,2,3,4].map(i=>`<button class="organize-item ${i===state.organizePage?'chosen':''}" data-organize="${i}"><b>${i}</b>${object()}<span>Page ${i}</span><i>≡</i></button>`).join('')}</div><div class="organize-actions"><button data-organize-action="duplicate">Duplicate</button><button data-organize-action="move">Move to end</button><button data-organize-action="delete">Delete</button></div><button class="primary" data-go="export">Save page order</button>${confirm}`}
function exportScreen(){return `${nav('Export 4 pages')}<p class="label">FORMAT</p><div class="format">${['PDF','JPG','PNG'].map(x=>`<button class="${state.format===x?'active':''}" data-format="${x}"><b>${x}</b>${x==='PDF'?'Document':x==='JPG'?'4 images':'Lossless'}</button>`).join('')}</div><p class="label">QUALITY</p><div class="qualities">${[['Small file','1.9 MB'],['Recommended','4.8 MB'],['Best quality','11.2 MB']].map(([q,s])=>`<button class="quality ${state.quality===q?'active':''}" data-quality="${q}" data-size="${s}"><i></i><span><b>${q}</b><small>${s}</small></span></button>`).join('')}</div><button class="ocr-row" data-ocr aria-pressed="${state.ocr}"><span><b>Searchable text</b><small>Keep recognized text selectable</small></span><i class="switch ${state.ocr?'on':''}"></i></button><div class="summary"><span>Algebra-notes.${state.format.toLowerCase()}</span><b>${state.quality==='Small file'?'1.9 MB':state.quality==='Best quality'?'11.2 MB':'4.8 MB'}</b></div><button class="primary" data-export>Export ${state.format}</button>`}
function success(){if(state.processing)return `<div class="processing"><div class="progress-ring" style="--progress:${state.progress}%"><b>${state.progress}%</b></div><h3>Creating your ${state.format}</h3><p>Optimizing selected pages. You can leave safely.</p><button class="secondary" data-cancel>Cancel export</button></div>`;return `<div class="success"><object data="${asset('export-success')}" type="image/svg+xml"></object><h3>Your ${state.format} is ready</h3><p>4 pages · ${state.quality==='Small file'?'1.9 MB':state.quality==='Best quality'?'11.2 MB':'4.7 MB'} · Searchable</p><button class="primary" data-toast="System share sheet would open">Share ${state.format}</button><button class="secondary" data-toast="Saved to Files">Save to Files</button><button class="secondary" data-go="library">Back to library</button></div>`}

const views={library,camera,select,actions,crop,enhance,organize,export:exportScreen,success};
function render(direction='forward'){
  const screen=screens[state.index];root.className=`prototype-screen enter-${direction}`;root.innerHTML=views[screen.id]();
  document.querySelector('#step-label').textContent=`STEP ${String(state.index+1).padStart(2,'0')} / ${String(screens.length).padStart(2,'0')}`;document.querySelector('#screen-name').textContent=screen.name;document.querySelector('#screen-purpose').textContent=screen.purpose;document.querySelector('#note-title').textContent=screen.note;document.querySelector('#note-copy').textContent=screen.copy;
  document.querySelector('#previous').disabled=state.index===0;document.querySelector('#next').disabled=state.index===screens.length-1;
  document.querySelector('#flow-progress').innerHTML=screens.map((_,i)=>`<i class="${i===state.index?'active':''}"></i>`).join('');
  [...list.querySelectorAll('button')].forEach((button,i)=>button.classList.toggle('active',i===state.index));
  stateSummary.textContent=screen.id==='camera'?`${state.cameraMode} · Batch ${state.camera.batch?'on':'off'} · Flash ${state.camera.flash?'on':'off'} · Auto ${state.camera.auto?'on':'off'}`:screen.id==='select'?`${state.documentStatus} · ${state.selected.size} selected`:screen.id==='crop'?`${state.cropPreset} · ${100-state.cropInset*2}% area`:screen.id==='enhance'?`${state.filter} · ${state.filter==='Original'?0:state.strength}%`:screen.id==='export'?`${state.format} · ${state.quality}`:state.processing?`Export ${state.progress}%`:'Ready';
  bind();
}

function bind(){
  root.querySelectorAll('[data-go]').forEach(el=>el.addEventListener('click',()=>{log(`Opened ${el.dataset.go}`);go(el.dataset.go)}));
  root.querySelectorAll('[data-open-document]').forEach(el=>el.addEventListener('click',()=>{const saved=el.dataset.openDocument==='saved';state.documentName=saved?el.dataset.name:'Untitled scan';state.documentStatus=saved?'Saved · changes autosave':'Draft · autosaved';state.selected=new Set([0]);log(`Opened ${saved?'saved document':'draft'} for re-editing`);go('select')}));
  root.querySelectorAll('[data-back]').forEach(el=>el.addEventListener('click',()=>back()));
  root.querySelectorAll('[data-camera]').forEach(el=>el.addEventListener('click',event=>{event.stopPropagation();const key=el.dataset.camera;state.camera[key]=!state.camera[key];log(`${key} turned ${state.camera[key]?'on':'off'}`);render()}));
  root.querySelectorAll('[data-settings]').forEach(el=>el.addEventListener('click',()=>{state.settings=true;log('Opened camera settings');render()}));
  root.querySelectorAll('[data-close-settings]').forEach(el=>el.addEventListener('click',()=>{state.settings=false;log('Closed camera settings');render()}));
  root.querySelectorAll('[data-camera-mode]').forEach(el=>el.addEventListener('click',()=>{state.cameraMode=el.dataset.cameraMode;log(`${state.cameraMode} capture mode selected`);render()}));
  root.querySelectorAll('[data-shutter]').forEach(el=>el.addEventListener('click',()=>{const added=state.cameraMode==='Book'?2:state.cameraMode==='QR'?0:1;state.pageCount+=added;const message=state.cameraMode==='Book'?'Book spread captured as left and right pages':state.cameraMode==='Text'?'Recognized text captured':state.cameraMode==='OCR Doc'?'Page captured for high-accuracy OCR':state.cameraMode==='QR'?'QR payload detected and ready to open':'Page captured';log(message);const flash=root.querySelector('.camera-flash');flash?.classList.add('fire');el.animate([{transform:'scale(1)'},{transform:'scale(.82)'},{transform:'scale(1)'}],{duration:280});setTimeout(()=>{render();showToast(message)},300)}));
  root.querySelectorAll('[data-open-photos]').forEach(el=>el.addEventListener('click',()=>{state.photoPreview=true;log(`Opened preview of ${state.pageCount} captured photos`);render()}));
  root.querySelectorAll('[data-close-photos]').forEach(el=>el.addEventListener('click',()=>{state.photoPreview=false;log('Closed captured photos preview');render()}));
  root.querySelectorAll('[data-photo-page]').forEach(el=>el.addEventListener('click',()=>showToast(`Captured page ${el.dataset.photoPage} selected`)));
  root.querySelectorAll('[data-review-photos]').forEach(el=>el.addEventListener('click',()=>{state.photoPreview=false;go('select');log('Opened full captured-page review')}));
  root.querySelectorAll('[data-discard-capture]').forEach(el=>el.addEventListener('click',()=>{state.confirmDiscard=true;log('Discard confirmation opened');render()}));
  root.querySelectorAll('[data-cancel-discard]').forEach(el=>el.addEventListener('click',()=>{state.confirmDiscard=false;log('Discard cancelled; photos kept');render()}));
  root.querySelectorAll('[data-confirm-discard]').forEach(el=>el.addEventListener('click',()=>{const count=state.pageCount;state.pageCount=0;state.selected.clear();state.draftSaved=false;state.confirmDiscard=false;go('library','back');showToast(`${count} captured photos discarded permanently`);log(`Discarded ${count} photos and all capture changes`)}));
  root.querySelectorAll('[data-page]').forEach(el=>el.addEventListener('click',()=>{const i=Number(el.dataset.page);state.selected.has(i)?state.selected.delete(i):state.selected.add(i);log(`Selection changed to ${state.selected.size} pages`);render()}));
  root.querySelectorAll('[data-action-sheet]').forEach(el=>el.addEventListener('click',()=>{state.actionKey=el.dataset.actionSheet;state.actionSheet=actionData[state.actionKey];state.history.push(state.index);state.index=3;log(`Opened ${state.actionKey} actions`);render()}));
  root.querySelectorAll('[data-choice]').forEach(el=>el.addEventListener('click',()=>{const choice=Number(el.dataset.choice);const key=state.actionKey||'enhance';if(key==='enhance')go('enhance');else if(key==='organize')go('organize');else if(key==='rotate'){back();showToast(choice===0?'Rotated left':choice===1?'Rotated right':'Crop review opened','Undo')}else showToast(['Text extraction queued','Selected pages ready to export','Page details opened'][choice]||'Action complete')}));
  root.querySelectorAll('[data-action]').forEach(el=>el.addEventListener('click',()=>{const action=el.dataset.action;if(action==='all'){state.selected=state.selected.size===6?new Set():new Set([0,1,2,3,4,5]);log(state.selected.size?'Selected all pages':'Cleared selection');render()}else if(action)go(action)}));
  root.querySelectorAll('[data-filter]').forEach(el=>el.addEventListener('click',()=>{state.filter=el.dataset.filter;log(`${state.filter} filter selected`);render()}));
  root.querySelectorAll('[data-reset-filter]').forEach(el=>el.addEventListener('click',()=>{state.filter='Original';state.strength=72;log('Filter reset to Original');render()}));
  root.querySelectorAll('[data-crop-preset]').forEach(el=>el.addEventListener('click',()=>{state.cropPreset=el.dataset.cropPreset;state.cropInset=state.cropPreset==='Full image'?2:12;log(`${state.cropPreset} crop selected`);render()}));
  root.querySelectorAll('[data-crop-inset]').forEach(el=>el.addEventListener('input',()=>{state.cropInset=Number(el.value);el.previousElementSibling.textContent=`${100-state.cropInset*2}%`;stateSummary.textContent=`Custom crop · ${100-state.cropInset*2}% area`}));
  root.querySelectorAll('[data-reset-crop]').forEach(el=>el.addEventListener('click',()=>{state.cropPreset='Detected edges';state.cropInset=12;log('Crop reset to detected edges');render()}));
  root.querySelectorAll('[data-save-edit]').forEach(el=>el.addEventListener('click',()=>{const kind=el.dataset.saveEdit;state.documentStatus=state.documentStatus.startsWith('Saved')?'Saved · changes autosaved':'Draft · autosaved';go('select','back');setTimeout(()=>showToast(`${kind==='crop'?'Crop':'Filter'} saved · original retained`),10)}));
  root.querySelectorAll('[data-strength]').forEach(el=>el.addEventListener('input',()=>{state.strength=Number(el.value);el.previousElementSibling.textContent=`${state.strength}%`;stateSummary.textContent=`${state.filter} · ${state.strength}%`}));
  root.querySelectorAll('[data-format]').forEach(el=>el.addEventListener('click',()=>{state.format=el.dataset.format;log(`${state.format} format selected`);render()}));
  root.querySelectorAll('[data-quality]').forEach(el=>el.addEventListener('click',()=>{state.quality=el.dataset.quality;log(`${state.quality} quality selected`);render()}));
  root.querySelectorAll('[data-ocr]').forEach(el=>el.addEventListener('click',()=>{state.ocr=!state.ocr;log(`Searchable text turned ${state.ocr?'on':'off'}`);render()}));
  root.querySelectorAll('[data-organize]').forEach(el=>el.addEventListener('click',()=>{state.organizePage=Number(el.dataset.organize);log(`Page ${state.organizePage} selected`);render()}));
  root.querySelectorAll('[data-organize-action]').forEach(el=>el.addEventListener('click',()=>{const action=el.dataset.organizeAction;if(action==='delete'){state.confirmDelete=true;render()}else showToast(action==='duplicate'?`Page ${state.organizePage} duplicated`:`Page ${state.organizePage} moved to end`,'Undo')}));
  root.querySelectorAll('[data-cancel-delete]').forEach(el=>el.addEventListener('click',()=>{state.confirmDelete=false;log('Delete cancelled');render()}));
  root.querySelectorAll('[data-confirm-delete]').forEach(el=>el.addEventListener('click',()=>{const deleted=state.organizePage;state.confirmDelete=false;render();showToast(`Page ${deleted} deleted`,'Undo');log(`Deleted page ${deleted}`)}));
  root.querySelectorAll('[data-export]').forEach(el=>el.addEventListener('click',startExport));
  root.querySelectorAll('[data-cancel]').forEach(el=>el.addEventListener('click',()=>{clearInterval(progressTimer);state.processing=false;state.progress=0;state.index=screens.findIndex(s=>s.id==='export');log('Export cancelled safely');render('back')}));
  root.querySelectorAll('[data-toast]').forEach(el=>el.addEventListener('click',()=>showToast(el.dataset.toast)));
  const thumbnails=[...root.querySelectorAll('.filter-thumb img[data-src]')];
  if(thumbnails.length){const load=()=>thumbnails.forEach((img,index)=>setTimeout(()=>{if(img.dataset.src){img.src=img.dataset.src;img.removeAttribute('data-src')}},index*45));const preview=root.querySelector('.edit-preview object');preview?.addEventListener('load',load,{once:true});setTimeout(load,350)}
}

function showToast(message,action='') {root.querySelector('.in-app-toast')?.remove();const toast=document.createElement('div');toast.className='in-app-toast';toast.innerHTML=`<span>${message}</span>${action?`<button>${action}</button>`:''}`;root.append(toast);log(message);toast.querySelector('button')?.addEventListener('click',()=>{log(`${action}: ${message}`);toast.remove()});setTimeout(()=>toast.remove(),4200)}

function startExport(){state.index=screens.findIndex(s=>s.id==='success');state.processing=true;state.progress=0;log(`Started ${state.format} export`);render();clearInterval(progressTimer);progressTimer=setInterval(()=>{state.progress=Math.min(100,state.progress+8);render();if(state.progress===100){clearInterval(progressTimer);setTimeout(()=>{state.processing=false;log(`${state.format} export complete`);render()},350)}},140)}

list.innerHTML=screens.map((s,i)=>`<li><button data-index="${i}"><i>${String(i+1).padStart(2,'0')}</i>${s.name}</button></li>`).join('');
list.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>go(Number(button.dataset.index),Number(button.dataset.index)<state.index?'back':'forward')));
document.querySelector('#previous').addEventListener('click',()=>go(state.index-1,'back'));document.querySelector('#next').addEventListener('click',()=>go(state.index+1));
document.querySelector('#restart').addEventListener('click',()=>{clearInterval(progressTimer);Object.assign(state,initialState());log('Prototype restarted');render('back')});
document.querySelector('#hotspots').addEventListener('click',event=>{const on=document.body.classList.toggle('hotspot-mode');event.currentTarget.setAttribute('aria-pressed',String(on));event.currentTarget.textContent=on?'◉ Hide hotspots':'◎ Show hotspots'});
document.addEventListener('keydown',event=>{if(event.key==='ArrowRight')go(state.index+1);if(event.key==='ArrowLeft')go(state.index-1,'back');if(event.key==='Escape'&&(state.settings||state.photoPreview||state.confirmDiscard)){state.settings=false;state.photoPreview=false;state.confirmDiscard=false;log('Dialog closed; photos kept');render()}});
let touchStart=0;document.querySelector('#device').addEventListener('pointerdown',event=>touchStart=event.clientX);document.querySelector('#device').addEventListener('pointerup',event=>{const delta=event.clientX-touchStart;if(Math.abs(delta)>75)go(state.index+(delta<0?1:-1),delta<0?'forward':'back')});
render();
